# Generated by Django 4.2.1 on 2023-05-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('translation', models.CharField(max_length=64)),
                ('sentences', models.JSONField()),
                ('chosen', models.BooleanField()),
                ('review_date', models.DateField()),
            ],
        ),
    ]
