# Generated by Django 4.2.1 on 2023-05-31 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='learned_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='word',
            name='stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='chosen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='review_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='word',
            name='sentences',
            field=models.CharField(max_length=1024),
        ),
    ]
