# Generated by Django 4.2.1 on 2023-05-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_word_learned_date_word_stage_alter_word_chosen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
    ]
